// This file is automatically generated by scripts/generate-manifest.mjs
// Do not edit this file directly.
export const PWA_CACHE_VERSION = 'dev-build';
export const PWA_BUILD_TIMESTAMP = '2025-01-01T00:00:00.000Z';
